apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: career-connect-backend
  namespace: monitoring
  labels:
    release: monitoring

spec:
  namespaceSelector:
    matchNames:
      - career-connect

  selector:
    matchLabels:
      app: backend

  endpoints:
    - port: http
      path: /metrics
      interval: 15s